# Generated by Django 4.0.4 on 2022-06-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tafe', '0002_notification_sent_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tafe.campus'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tafe.industry'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tafe.region'),
        ),
    ]
