# Generated by Django 4.0.4 on 2022-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafe', '0003_alter_notification_campus_alter_notification_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('infoLink', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
    ]
